# Generated by Django 5.2.17 on 2026-08-24 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='invoice_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='list_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='pricing_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='pricing_mode',
            field=models.CharField(default='NEW', help_text='PREVIOUS, COPY_EDIT, or NEW. Owner must confirm before save.', max_length=16),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='supplier_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='supplier_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, help_text='Effective cost after supplier discount. Historical; never overwrite.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='safe_selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Owner-approved floor. Software must not impose this automatically.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
