# Generated by Django 5.2.17 on 2026-08-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('shop_name', models.CharField(default='MM Electricals', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('gstin', models.CharField(blank=True, default='', max_length=32)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('invoice_prefix', models.CharField(default='MM', max_length=16)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('default_tax_inclusive', models.BooleanField(default=False)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('backup_retention_count', models.PositiveIntegerField(default=14)),
                ('scheduled_backup_enabled', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Extensible bag for future pricing and notification settings.')),
            ],
            options={
                'verbose_name': 'application settings',
                'verbose_name_plural': 'application settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('entity', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='api', max_length=64)),
                ('actor', models.CharField(default='system', max_length=128)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity', 'entity_id'], name='core_auditl_entity_d1c59f_idx')],
            },
        ),
    ]
