# Generated by Django 5.2.17 on 2026-08-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='inventory_valuation_method',
            field=models.CharField(default='FIFO', help_text='FIFO is the Phase 2 default. Weighted average can be plugged in later.', max_length=32),
        ),
    ]
