# Generated by Django 5.2.17 on 2026-08-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicationsettings_inventory_valuation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='enforce_safe_selling_price',
            field=models.BooleanField(default=False, help_text='If true, sales below safe price are blocked. Phase 3 default is warn-and-override.'),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='purchase_invoice_prefix',
            field=models.CharField(default='PUR', max_length=16),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='sale_invoice_prefix',
            field=models.CharField(default='MM', max_length=16),
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(db_index=True, max_length=32)),
                ('financial_year', models.CharField(db_index=True, max_length=9)),
                ('prefix', models.CharField(default='MM', max_length=16)),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('document_type', 'financial_year')},
            },
        ),
    ]
