export const ReportsPage = () => {
  const today = new Date().toISOString().slice(0, 10);
  const from = `${today.slice(0, 8)}01`;
  const q = `date_from=${from}&date_to=${today}`;
  const reports = ["sales", "profit", "inventory", "purchases", "vendors", "customers", "expenses"];
  return (
    <section>
      <h2 className="text-3xl">Reports</h2>
      <p className="mt-2 max-w-2xl font-sans text-sm text-[var(--muted)]">
        CSV files are generated by Django from the same aggregations as Analytics. Print uses the browser dialog.
      </p>
      <ul className="mt-6 space-y-2 font-sans text-sm">
        {reports.map((report) => (
          <li key={report}>
            <a className="underline" href={`/api/v1/analytics/export/${report}/?${q}`}>Download {report} CSV</a>
          </li>
        ))}
      </ul>
      <button type="button" className="mt-6 rounded-md border px-3 py-2 font-sans text-sm" onClick={() => window.print()}>
        Print this page
      </button>
    </section>
  );
};
