# Generated by Django 5.2.17 on 2026-08-24 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], db_index=True, max_length=16)),
                ('party_id', models.PositiveIntegerField(db_index=True)),
                ('payment_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK', 'Bank transfer'), ('CREDIT', 'Credit'), ('MIXED', 'Partial / mixed')], default='CASH', max_length=16)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], db_index=True, max_length=16)),
                ('party_id', models.PositiveIntegerField(db_index=True)),
                ('entry_date', models.DateField(db_index=True)),
                ('entry_type', models.CharField(choices=[('OPENING', 'Opening balance'), ('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('SALE_RETURN', 'Sale return'), ('PURCHASE_RETURN', 'Purchase return'), ('ADJUSTMENT', 'Adjustment')], max_length=32)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_type', models.CharField(blank=True, default='', max_length=64)),
                ('reference_id', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['entry_date', 'id'],
                'indexes': [models.Index(fields=['party_type', 'party_id', 'entry_date'], name='payments_le_party_t_fbbf31_idx')],
            },
        ),
    ]
